name: Release on Main

on:
  push:
    branches:
        - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.2.2

    - name: Create zip file
      run: zip -r project.zip ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v0.0.3
        release_name: Release ${{ github.run_number }}
